[package]
name = "lru_time_cache"
version = "0.2.2"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Provides a Least Recently Used [caching algorithm](http://en.wikipedia.org/wiki/Cache_algorithms) in a container which may be limited by size or time, reordered to most recently seen."
documentation = "http://maidsafe.net/lru_time_cache/latest"
repository = "https://github.com/maidsafe/lru_time_cache"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
time = "*"
rand = "*"
