[package]
name = "lru_time_cache"
version = "0.1.4"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Provides a Last Recently Used [caching algorithm](http://en.wikipedia.org/wiki/Cache_algorithms) in a container which may be limited by size or time, reordered to most recently seen."
documentation = "http://dirvine.github.io/lru_time_cache/"
repository = "https://github.com/dirvine/lru_time_cache"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
time = "*"
rand = "*"
